from behave import given, then, use_step_matcher, when

from features.support import zpp_support as support

use_step_matcher('parse')
given('ZPP is installed')(support.step_installed)
given('a clean user home')(support.step_clean_home)
given('a clean user home with an initialized global ZPP layer')(support.step_clean_initialized_home)
given('a clean user home with initialized ZPP state')(support.step_clean_initialized_home)
given('a project without local ZPP state')(support.step_clean_project)
given('the current project has no repository-local agent integration')(support.step_clean_project)
given('no interactive terminal is available')(support.step_noninteractive)
given('rg, jq, and zmem are unavailable on PATH')(support.step_tool_traits_unavailable)
given('an interactive terminal is available')(support.step_interactive)
given('valid initialized user state')(support.step_initialized)
given('a valid initialized ZPP user state')(support.step_initialized)
given('partially initialized valid user state with missing required entries')(support.step_partial_user_state)
given('the existing managed files have distinguishable valid formatting')(support.step_distinct_user_bytes)
given('user state contains an invalid managed source')(support.step_invalid_user_state)
given('other required user-state entries are missing')(support.step_missing_user_entries)
given('Pi, Codex, and Claude Code have no ZPP integration')(support.step_no_agent_integrations)
given('Claude Code has the exact historical ZPP-managed SessionStart hook invoking zpp resolve')(support.step_exact_historical_claude_hook)
given('every other Claude Code destination required by workflow installation can be updated safely')(support.step_other_claude_destinations_safe)
then('the historical hook is replaced by the current agent-qualified ZPP lifecycle integration')(support.step_historical_hook_upgraded)
then('the current Claude Code codespace guards are installed')(support.step_current_claude_guard_installed)
then('unrelated Claude Code settings are byte-for-byte unchanged')(support.step_unrelated_claude_settings_preserved)
given('Claude Code has a user-authored SessionStart hook resembling the historical ZPP hook')(support.step_ambiguous_historical_claude_hook)
given('every Claude Code integration destination is recorded')(support.step_record_claude_integration_destinations)
then('every Claude Code integration destination is byte-for-byte unchanged')(support.step_claude_integration_destinations_unchanged)
when('the user requests the ZPP version')(support.step_version)
when('the user requests ZPP help')(support.step_help)
when('the user runs zpp init')(support.step_run_init)
when('the user runs zpp init twice')(support.step_run_init_twice)
when('the user runs zpp init with agents Pi and Codex')(support.step_init_pi_codex)
when('the user runs zpp init with agent Pi twice')(support.step_init_pi_twice)
when('the user runs zpp init and selects Claude Code')(support.step_select_claude)
when('the user runs zpp init and submits the selector with no checked agent')(support.step_select_none)
when('the user cancels zpp init from the agent selector')(support.step_cancel_selector)
when('the user runs zpp init with agent Claude Code')(support.step_init_claude)
when('the user runs zpp init with an unsupported agent name')(support.step_bad_agent)
then('the product identifies itself as ZPP version 0.9.0')(support.step_assert_version)
then('the help exposes the confirmed initial command surface')(support.step_assert_help)
then('the help exposes the independent workflow lifecycle command group')(support.step_workflow_command_group)
then('the help does not expose a generic skill command group')(support.step_no_generic_skill_command_group)
then('initialization succeeds')(support.step_init_succeeds)
then('initialization succeeds both times')(support.step_two_inits_succeed)
then('both initializations succeed without offering agent selection')(support.step_two_inits_succeed)
then('the neutral global trait layer exists')(support.step_global_exists)
then('the neutral global user state is initialized')(support.step_global_exists)
then('the saved and cache roots exist')(support.step_empty_roots)
then('no cache artifact exists')(support.step_no_cache)
then('no trait cache is created')(support.step_no_cache)
then('the project still has no local ZPP state')(support.step_no_local_state)
then('no agent application is configured')(support.step_no_agents)
then('no agent application is changed')(support.step_no_agents)
then('every missing required user-state entry is created')(support.step_missing_created)
then('every pre-existing managed file is byte-for-byte unchanged')(support.step_preserved_files)
then('the second initialization makes no further change')(support.step_second_unchanged)
then('initialization fails as a managed-state rejection')(support.step_managed_rejection)
then('agent setup fails as a managed-state rejection')(support.step_managed_rejection)
then('the diagnostic identifies the invalid source path')(support.step_invalid_diagnostic)
then('the diagnostic identifies the invalid managed source')(support.step_invalid_diagnostic)
then('the diagnostic identifies the invalid managed source path')(support.step_invalid_managed_path)
then('no missing user-state entry is created')(support.step_no_missing_created)
then('the existing user state is unchanged')(support.step_user_unchanged)
then('initialization succeeds without offering agent selection')(support.step_init_no_selector)
then('one selector offers Pi, Codex, and Claude Code')(support.step_selector_offers)
then('{label} has one ZPP-managed native lifecycle hook')(support.step_agent_installed)
then('neither agent receives a ZPP instruction paragraph or skill')(support.step_no_policy_install)
then('Claude Code receives no ZPP instruction paragraph or skill')(support.step_no_policy_install)
then('their agent-owned hook trust and enablement state is unchanged')(support.step_trust_unchanged)
then('Claude Code is unchanged')(support.step_claude_unchanged)
then('Pi and Codex are unchanged')(support.step_pi_codex_unchanged)
then('the current project still has no repository-local agent integration')(support.step_no_repo_agent)
then('initialization is cancelled')(support.step_cancelled)
given('valid initialized user state contains an activatable authored trait')(support.step_activatable_state)
given('no trait cache exists')(support.step_no_trait_cache)
given('Pi has a ZPP integration surrounded by unmanaged content')(support.step_pi_surrounded)
given('Codex was previously configured by ZPP')(support.step_codex_existing)
then('Pi has exactly one valid ZPP integration')(support.step_one_pi_integration)
then("Pi's unmanaged content is byte-for-byte unchanged")(support.step_pi_unmanaged_unchanged)
then('Codex remains installed and unchanged')(support.step_codex_still)
then("no effective trait, workflow direction, or platform guidance is copied into Pi's installed hook")(support.step_pi_no_trait_copy)
then('trait resolution is not invoked')(support.step_resolution_not_invoked)
given('{agent} was configured by ZPP')(support.step_agent_configured)
given('its native hook is trusted and enabled by the agent application')(support.step_hook_enabled)
given('its current working directory resolves one effective trait document')(support.step_hook_one_trait)
given('its current working directory resolves no active traits')(support.step_hook_empty)
given('its current working directory causes trait resolution to fail')(support.step_hook_failure)
use_step_matcher('re')
when('(?:.+ )?invokes the ZPP hook')(support.step_invoke_hook)
when('the native ZPP hook is invoked')(support.step_invoke_hook)
use_step_matcher('parse')
then('ZPP resolves the current working directory with {agent} as the invoking agent')(support.step_hook_cwd)
then("only {agent}'s active plugin trait sources are eligible")(support.step_hook_agent_plugins)
then('the complete effective trait document is injected exactly once into {agent} context')(support.step_hook_injected)
then('hook execution succeeds')(support.step_hook_success)
then('no ZPP trait context is injected into {agent}')(support.step_hook_no_context)
then('the resolution failure is surfaced through {agent}')(support.step_hook_failure_surfaced)
then('no stale or partial ZPP trait context is injected')(support.step_no_stale_context)
given('Claude Code has an unmanaged hook conflicting with ZPP integration')(support.step_claude_conflict)
given('Pi has no ZPP integration')(support.step_pi_missing)
given('Codex has an unmanaged hook conflicting with ZPP integration')(support.step_codex_conflict)
then('the diagnostic identifies the conflicting path')(support.step_conflict_path)
then('the conflicting unmanaged hook is unchanged')(support.step_conflict_unchanged)
then('the conflicting Codex hook remains unchanged')(support.step_conflict_unchanged)
then('all other Claude Code content is unchanged')(support.step_claude_content_unchanged)
then('Pi remains unchanged')(support.step_pi_unchanged)
then('the invocation fails as a usage error')(support.step_usage_error)
then('no ZPP user state is created')(support.step_no_user_state)
given('a valid profile named "{name}" with distinctive authored bytes')(support.step_existing_profile)
given('no profile named "{name}" exists')(support.step_no_named_profile)
given('profile "{name}" has invalid managed state and a required artifact absent')(support.step_broken_profile)
given('the complete ZPP user state is recorded')(support.step_record_user_state)
use_step_matcher('re')
when('the user runs (?P<command>zpp (?:profile|local)(?!.* and declines confirmation).+)')(support.step_run_profile_or_local)
use_step_matcher('parse')
then('both profile creations succeed')(support.step_last_two_succeed)
then('both saved creations succeed')(support.step_last_two_succeed)
then('the authored bytes of profile "alpha" are unchanged')(support.step_profile_bytes)
then('profile "beta" contains one neutral authored ZPP layer')(support.step_beta_neutral)
then('neither profile has a derived cache')(support.step_profiles_no_cache)
then('the command succeeds with stdout:')(support.step_stdout_docstring)
then('the command is rejected with exit code 1')(support.step_exit_one)
then('resolution fails with exit code 1')(support.step_exit_one)
use_step_matcher('re')
then('the diagnostic identifies (?P<subject>the invalid profile name|the invalid saved name|the invalid managed source|the missing source profile|the existing destination|the persistent default profile|".+")')(support.step_diagnostic_subject)
use_step_matcher('parse')
then('the complete ZPP user state is unchanged')(support.step_complete_user_unchanged)
given('profiles "work" and "keep" and their independent caches exist')(support.step_profiles_and_caches)
given('ZPP_PROFILE is "work"')(support.step_profile_env)
when('the user runs zpp profile remove work and declines confirmation')(support.step_decline_profile)
then('profile "work" and its cache remain unchanged')(support.step_work_remains)
then('profile "work" and its independent cache no longer exist')(support.step_work_removed)
then('profile "keep" and its independent cache are unchanged')(support.step_keep_profile)
then('ZPP_PROFILE remains "work"')(support.step_env_unchanged)
then('the command succeeds')(support.step_command_succeeds)
then('the command succeeds with empty stdout')(support.step_empty_stdout)
use_step_matcher('re')
given('"(?P<path>C:\\\\work\\\\[ab])" is an existing directory and no saved layer named "(?P<name>.+)" exists')(support.step_saved_target)
use_step_matcher('parse')
then('the saved creation succeeds')(support.step_saved_succeeds)
then('one authored layer exists at ~/.zpp/saved/shared')(support.step_saved_layer)
then('saved layer "shared" is one neutral authored ZPP layer')(support.step_saved_layer)
then('no saved layer named "shared" exists under ~/.zpp/profiles')(support.step_saved_not_profile)
then('no independent cache exists for saved layer "shared"')(support.step_saved_no_cache)
then('the command succeeds with these saved bindings in canonical-target order:')(support.step_saved_table)
given('an existing saved layer named "shared" with distinctive authored bytes bound to "C:\\work\\b"')(support.step_existing_saved)
given('"C:\\work\\a" is an existing directory')(support.step_work_a)
given('"c:/WORK/B" identifies the same Windows target as "C:\\work\\b"')(support.step_equivalent_b)
when('the user repeats zpp profile saved create shared "c:/WORK/B"')(support.step_repeat_saved)
then('the authored bytes of saved layer "shared" are unchanged')(support.step_saved_bytes)
then('the saved index maps exactly both canonical absolute targets to "shared"')(support.step_two_bindings)
given('"C:\\work\\a" is canonically bound to saved layer "shared"')(support.step_bound_shared)
given('no saved layer named "other" exists')(support.step_no_other_saved)
use_step_matcher('re')
given('"(?P<path>C:\\\\missing)" does not exist and no saved layer named "new" exists')(support.step_missing_saved_target)
given('"(?P<path>C:\\\\work\\\\file\\.txt)" is an existing file and no saved layer named "new" exists')(support.step_file_saved_target)
use_step_matcher('parse')
given('saved layer "broken" has invalid managed state and "C:\\work\\a" is an existing directory')(support.step_broken_saved)
given('saved layer "shared" has two target bindings and an independent cache')(support.step_shared_two_cache)
given('saved layer "keep" has the canonical target binding "C:\\work\\keep" and an independent cache')(support.step_keep_saved)
when('the user runs zpp profile saved remove shared and declines confirmation')(support.step_decline_saved)
then('saved layer "shared", its bindings, and its cache remain unchanged')(support.step_shared_remains)
then('every binding for "shared" is absent from the saved index')(support.step_shared_bindings_removed)
then('saved layer "shared" and its independent cache no longer exist')(support.step_shared_removed)
then('saved layer "keep", its binding, and its independent cache are unchanged')(support.step_keep_saved_unchanged)
given('the current working directory is the root of a Git worktree')(support.step_git_root)
given('an existing directory "src\\nested" is inside that worktree')(support.step_nested_dir)
given('neither target has local ZPP state')(support.step_no_target_layers)
when('the user repeats zpp local init "src"')(support.step_local_explicit)
then('both local initializations succeed')(support.step_local_success)
then('each target contains one neutral authored ZPP layer')(support.step_each_local)
then('neither target contains derived cache state')(support.step_no_local_caches)
then('no other directory gains local ZPP state')(support.step_only_expected_local)
given('an existing Git-worktree directory "src"')(support.step_git_src)
given('"src/.zpp" contains valid distinctive trait.json and config.json bytes')(support.step_distinct_local)
given('"src/.zpp/traits" is absent')(support.step_traits_absent)
then('the distinctive authored bytes are unchanged')(support.step_local_bytes)
then('"src/.zpp/traits" exists as a directory')(support.step_local_traits)
then('"src/.zpp" contains no derived cache state')(support.step_local_no_cache)
given('"src/.zpp" contains an invalid managed source')(support.step_invalid_local)
given('another required local-layer artifact is absent')(support.step_missing_local_artifact)
given('the complete worktree state is recorded')(support.step_record_worktree)
given('the complete surrounding state is recorded')(support.step_record_worktree)
then('the complete worktree state is unchanged')(support.step_worktree_unchanged)
then('the complete surrounding state is unchanged')(support.step_worktree_unchanged)
use_step_matcher('re')
given('"(?P<path>C:\\\\missing)" does not exist')(support.step_missing_target)
given('"(?P<path>C:\\\\work\\\\file\\.txt)" is an existing file')(support.step_file_target)
given('"(?P<path>C:\\\\outside)" is an existing directory outside Git')(support.step_outside_git)
use_step_matcher('parse')
given('an initialized global layer has multiple valid activated authored traits')(support.step_compilation_traits)
given('one trait omits optional frontmatter while another contains order, config, skill lookup, and UTF-8 text')(support.step_compilation_shape)
given('an inactive profile also has an authored trait')(support.step_inactive_profile)
given('no derived trait cache exists')(support.step_no_derived_cache)
when('the user runs zpp resolve for an existing directory')(support.step_resolve_target)
when('the user runs zpp resolve for an existing target')(support.step_resolve_target)
when('the user runs zpp resolve for the target')(support.step_resolve_target)
when('the user runs zpp resolve for the nested target')(support.step_resolve_target)
then('resolution succeeds with complete native documents for the activated global traits')(support.step_compilation_output)
then('the resolved bodies preserve their authored whitespace and UTF-8 text')(support.step_compilation_bodies)
then('the participating global layer gains one independent compiled cache')(support.step_global_cache)
then('no cache is created for the inactive profile')(support.step_inactive_no_cache)
then('every authored trait file remains byte-for-byte unchanged')(support.step_sources_unchanged)
given('an activated authored trait has previously been resolved')(support.step_previously_resolved)
given('its authored body changes after the derived cache was certified')(support.step_change_source)
when('the user runs zpp resolve for its target')(support.step_resolve_changed)
then('resolution succeeds with the changed advisory body')(support.step_changed_body)
then('no stale advisory body is returned')(support.step_no_old_body)
then('the authored trait remains authoritative')(support.step_authored_authority)
given('a participating layer has stale derived data')(support.step_stale_layer)
given('multiple authored traits in that layer are invalid')(support.step_multiple_invalid)
then('resolution fails as a managed-state rejection')(support.step_resolution_rejected)
then('stdout is empty')(support.step_stdout_empty)
then('stderr is empty')(support.step_stderr_empty)
then('stderr identifies every invalid authored source without a stack trace')(support.step_all_invalid_sources)
then('no valid subset or stale trait document is returned')(support.step_no_stale_subset)
given('the current directory is an existing target')(support.step_current_target)
given('the global layer authors a valid neutral trait')(support.step_global_neutral)
given('the global layer configures that trait')(support.step_global_configures)
given('the global trait trigger configuration is empty')(support.step_empty_triggers)
when('the user runs zpp resolve without a target argument')(support.step_resolve_default)
then('resolution succeeds')(support.step_resolution_success)
given('the global trait trigger configuration contains only that trait name')(support.step_conditionless)
then('stdout contains exactly the complete effective neutral trait document')(support.step_exact_neutral)
given('an existing target contains a matching workspace file for the second alternative of a workspace_contain rule')(support.step_workspace_match)
given('a fixture executable named neutral-tool is available on PATH')(support.step_fixture_tool)
given('matching decoy files exist only under .git, an independent cache directory, and a directory symlink')(support.step_decoys)
given('the composed trigger rules include matching which and workspace_contain rules for the same neutral trait')(support.step_matching_rules)
given('the composed trigger rules include traits whose only matches are the excluded decoys')(support.step_decoy_rules)
given('the composed trigger rules include a trait whose executable is unavailable')(support.step_unavailable_rule)
then('stdout contains the matching neutral trait exactly once')(support.step_neutral_once)
then('stdout contains no trait matched only through .git, an independent cache directory, or directory symlink traversal')(support.step_no_decoys)
then('stdout contains no trait whose executable is unavailable')(support.step_no_unavailable)
then('the resolved skill lookup remains passive frontmatter metadata')(support.step_skill_lookup_passive)
given('the global layer activates trait alpha')(support.step_global_alpha)
given('the repository-root layer sets trait_overwrites to true without a trait.json file')(support.step_root_overwrite)
given('a nested layer uses extending trigger behavior and activates trait beta')(support.step_nested_beta)
given('trait gamma is authored and configured but is not named by an active trigger')(support.step_gamma_config)
then('stdout contains exactly the effective trait document named beta')(support.step_only_beta)
given('an existing target is nested inside a Git worktree')(support.step_nested_worktree)
given('ZPP_PROFILE names an existing work profile')(support.step_work_profile)
given('global, work profile, repository-root, and root-to-target nested layers participate')(support.step_all_layers)
given('two saved bindings are ancestors of the target with different saved layer names')(support.step_two_saved_ancestors)
given('the closer saved binding is nested below the farther saved binding')(support.step_saved_closer)
given('each participating layer supplies a definition or configuration for the same activated neutral trait')(support.step_precedence_definitions)
given('the closest nested layer supplies the winning description, order, default config, skill lookup, and advisory body')(support.step_winning_nested)
given('successive traitsConfig values contain distinct keys and replacement values for the same nested object key')(support.step_distinct_overlays)
then('the work profile participates after global')(support.step_profile_participates)
then('only the closest matching saved layer participates')(support.step_only_close_saved)
then('repository layers participate from the repository root toward the target')(support.step_repo_layer_order)
then('the effective trait uses the complete document from the closest nested definition')(support.step_winning_document)
then('its effective config contains distinct layered keys')(support.step_layered_keys)
then('its latest nested object value replaces rather than recursively merges earlier nested object values')(support.step_shallow_nested)
given('an existing target is outside every Git worktree')(support.step_outside_worktree)
given('the target descends from a saved binding')(support.step_target_saved)
given('global and saved rules activate different neutral traits')(support.step_global_saved_rules)
then('stdout contains exactly the global and saved effective trait documents in order')(support.step_global_saved_output)
then('no repository or subfolder layer is required')(support.step_no_repo_required)
given('traits are first activated in the order alpha, beta, gamma, delta, epsilon, zeta')(support.step_order_traits)
given('one of those traits is activated by a later duplicate rule')(support.step_duplicate_activation)
given('gamma and delta have order 100')(support.step_order_characterized)
given('zeta has order 200')(support.step_order_characterized)
given('beta and epsilon have no order')(support.step_order_characterized)
given('alpha originally has an explicit order')(support.step_order_characterized)
given('a later layer completely replaces alpha with an authored document that has no order')(support.step_replace_alpha)
given('traitsConfig for zeta contains a config key named order')(support.step_config_order_key)
then('stdout contains exactly these effective trait documents in order:')(support.step_trait_order)
given('an activated neutral trait has all accepted frontmatter fields')(support.step_full_trait)
given('its description and advisory body contain UTF-8 text')(support.step_full_trait_characterized)
given('its advisory body contains deliberate whitespace')(support.step_full_trait_characterized)
given('a participating layer overrides part of its config')(support.step_full_overlay)
then('stdout contains exactly one complete Markdown trait document')(support.step_one_complete_doc)
then('its YAML frontmatter semantically contains name, description, order, effective config, and ordered skill_lookup')(support.step_complete_metadata)
then('its body preserves the authored UTF-8 text and whitespace')(support.step_body_exact)
then('the effective config contains the accepted shallow override')(support.step_effective_override)
given('the requested target does not exist')(support.step_invalid_missing_resolution)
given('the requested target exists as a file')(support.step_invalid_file_resolution)
given('ZPP_PROFILE names a profile that does not exist')(support.step_unknown_profile)
given('the saved index binds the target to a saved layer that does not exist')(support.step_missing_saved_layer)
when('the user runs zpp resolve for the missing target')(support.step_run_missing_resolve)
when('the user runs zpp resolve for the file target')(support.step_run_file_resolve)
use_step_matcher('re')
then('stderr identifies (?P<subject>the missing target|the file target|the unknown profile|the missing saved layer) without a stack trace')(support.step_resolution_diagnostic)
use_step_matcher('parse')
then('no fallback resolution is returned')(support.step_no_fallback)
when('the user runs zpp workflow install with agent Claude Code')(support.step_install_default_global_claude)
then('installation fails as a managed-state rejection')(support.step_skill_managed_rejection)
then('the persistent user-owned default profile exists')(support.step_default_profile_exists)
then('the default profile is provisioned without participating in resolution')(support.step_default_profile_inactive)
then('the default profile conditionlessly selects exactly automatic-workflow, codespace-claim-guard, zero-assumptions, and ponytail when explicitly used')(support.step_default_profile_triggers)
then('the default profile guards use-rg, use-jq, and use-zmem by their corresponding executables')(support.step_default_tool_guards)
then('the default profile contains all packaged platform workflow traits without activating them')(support.step_default_optional_platform_traits)
given('the default profile has valid user-authored changes with distinctive formatting')(support.step_user_edited_default)
then('the complete default profile is byte-for-byte unchanged')(support.step_user_default_preserved)
then('no bundled default content is reapplied')(support.step_user_default_preserved)
given('profile "source" has distinctive valid authored bytes and an independent cache')(support.step_copy_source_profile)
given('the global layer has distinctive authored bytes')(support.step_distinct_global_bytes)
then('profile "derived" contains a byte-for-byte copy of the authored source layer')(support.step_derived_profile_copy)
then('profile "derived" has no derived cache')(support.step_derived_has_no_cache)
then('profile "source" and its independent cache are unchanged')(support.step_copy_source_unchanged)
then('the global layer is unchanged')(support.step_global_unchanged)
given('profiles "source" and "existing" already exist')(support.step_source_and_existing_profiles)
given('profile "broken" has invalid managed state')(support.step_invalid_profile_for_copy)
given('the current timestamp for archive naming is 20260730-143522')(support.step_fixed_archive_time)
given('the global layer has distinctive valid authored bytes and derived state')(support.step_global_layer_for_activation)
given('the default profile has different distinctive valid authored bytes and derived state')(support.step_default_layer_for_activation)
when('the user runs zpp global activate {profile}')(support.step_activate_global_profile)
then('profile "20260730-143522-global" contains the prior global authored layer')(support.step_archived_global_layer)
then('the global layer contains a byte-for-byte copy of the default authored layer')(support.step_global_matches_default)
then('the default profile is byte-for-byte unchanged')(support.step_default_profile_unchanged)
then('no derived cache or modification sidecar is copied into either authored layer')(support.step_no_derived_state_copied)
then('affected derived caches are invalidated')(support.step_activation_cache_invalidated)
when('the user resolves traits without ZPP_PROFILE')(support.step_resolve_without_profile)
then('the platform-neutral base traits resolve from global')(support.step_base_traits_from_global)
given('profiles "work" and "default" exist')(support.step_work_and_default_profiles)
then('the default profile still exists unchanged')(support.step_default_still_unchanged)
given('ZPP_PROFILE is "default"')(support.step_default_profile_env)
then('automatic-workflow has effective mode "automatic"')(support.step_automatic_mode)
then('stdout contains no Python-specific trait')(support.step_no_python_traits)
given('the repository layer overrides automatic-workflow mode to "manual"')(support.step_local_manual_mode)
when('the user runs zpp resolve for the repository target')(support.step_resolve_repository_target)
then('automatic-workflow remains active with effective mode "manual"')(support.step_manual_mode_active)
then('the same platform-neutral base traits remain active')(support.step_same_base_traits)
then('codespace-claim-guard remains active')(support.step_claim_guard_remains_active)
use_step_matcher('re')
given('the repository layer additionally activates (?P<trait>python-(?:bdd|tdd|build|django-tdd)|typescript-(?:bdd|tdd)|flutter-(?:bdd|tdd))')(support.step_activate_optional_python_trait)
then('stdout contains (?P<trait>python-(?:bdd|tdd|build|django-tdd)|typescript-(?:bdd|tdd)|flutter-(?:bdd|tdd)) with only (?P<responsibility>Behave|pytest|the uv environment|Django testing|TypeScript BDD|TypeScript TDD|Flutter BDD|Flutter TDD) guidance')(support.step_optional_python_guidance)
use_step_matcher('parse')
then('stdout contains no other optional platform workflow trait')(support.step_no_other_python_trait)
given('automatic-workflow has effective mode "automatic"')(support.step_claim_workflow_automatic)
given('another active codespace claims the physical checkout targeted by a ZPP-managed mutation')(support.bind_claim_step(support.claim_given, 'another active codespace claims the physical checkout targeted by a ZPP-managed mutation'))
given('codespace-claim-guard is inactive for the target')(support.bind_claim_step(support.claim_given, 'codespace-claim-guard is inactive for the target'))
given('its shell work is associated with an active codespace and current checkout')(support.bind_claim_step(support.claim_given, 'its shell work is associated with an active codespace and current checkout'))
then('the installed ZPP guard rejects the mutation before the checkout changes')(support.bind_claim_step(support.claim_then, 'the installed ZPP guard rejects the mutation before the checkout changes'))
then('the conflict identifies the active owning codespace')(support.bind_claim_step(support.claim_then, 'the conflict identifies the active owning codespace'))
then('no OpenSpec workset is accepted as proof of write ownership')(support.bind_claim_step(support.claim_then, 'no OpenSpec workset is accepted as proof of write ownership'))
then('the installed ZPP guard verifies that codespace and current checkout association')(support.bind_claim_step(support.claim_then, 'the installed ZPP guard verifies that codespace and current checkout association'))
then('it does not claim to infer every path the arbitrary shell command may mutate')(support.bind_claim_step(support.claim_then, 'it does not claim to infer every path the arbitrary shell command may mutate'))
then('manual editor actions, unrelated processes, and unsupported tool paths remain outside its guarantee')(support.bind_claim_step(support.claim_then, 'manual editor actions, unrelated processes, and unsupported tool paths remain outside its guarantee'))
when('Pi attempts a supported direct edit or write tool call from a different codespace')(support.bind_claim_step(support.claim_when, 'Pi attempts a supported direct edit or write tool call from a different codespace'))
when('Pi submits a supported shell tool call')(support.bind_claim_step(support.claim_when, 'Pi submits a supported shell tool call'))
when('Codex attempts a supported direct edit or write tool call from a different codespace')(support.bind_claim_step(support.claim_when, 'Codex attempts a supported direct edit or write tool call from a different codespace'))
when('Codex submits a supported shell tool call')(support.bind_claim_step(support.claim_when, 'Codex submits a supported shell tool call'))
when('Claude Code attempts a supported direct edit or write tool call from a different codespace')(support.bind_claim_step(support.claim_when, 'Claude Code attempts a supported direct edit or write tool call from a different codespace'))
when('Claude Code submits a supported shell tool call')(support.bind_claim_step(support.claim_when, 'Claude Code submits a supported shell tool call'))
