from features.support.bindings import register_exact_steps

register_exact_steps(
    (
        "an unregistered repository contains ZPP context and trait documents",
        "a user explicitly invokes the workflow against that repository",
        "ZPP requests read-only invocation-scoped OpenLease bindings for those "
        "documents",
        "no trust initialization registration topology lease or space is created",
        "a repository contains ZPP trait documents",
        "no workflow or trait command targets that repository",
        "ZPP does not open evaluate register or mutate the documents",
        "the repository has no bdd trait document",
        "space and global bdd contributions are available",
        "a user invokes the workflow against the repository",
        "the repository document remains absent",
        "the available space and global contributions remain eligible",
        "the repository bdd trait document is absent",
        "a user runs trait init for bdd against that exact repository",
        "ZPP asks OpenLease to initialize exactly that bounded document",
        "no repository registration topology persistent source or space is created",
        "workflow resolution discovers a missing or outdated repository trait document",
        "no explicit mutation command was requested",
        "ZPP performs no initialization or managed write",
        "a user requests the ZPP workflow integration for a supported agent",
        "ZPP supplies its consolidated skill and native hook assets",
        "Agent Router owns discovery destination selection installation update and "
        "removal for both assets",
        "ZPP does not write an agent destination directly",
        "Codex and Claude Code have different active plugins providing ZPP traits",
        "a user resolves a repository with Codex as the invoking agent",
        "the router uses the real user home and that repository as project context",
        "only Codex effective active ZPP trait artifacts contribute",
        "a project workflow integration is selected for update",
        "ZPP updates the consolidated skill and native hook",
        "Agent Router explicitly replaces the selected project skill",
        "Agent Router reconciles its owned hook through native hook installation",
        "a user-scoped workflow integration is selected for install or update",
        "ZPP projects the consolidated skill and native hook",
        "Agent Router uses ownership-safe installation for both assets",
        "OpenLease rejects a document operation or Agent Router rejects a projection",
        "ZPP receives that component result",
        "ZPP reports the rejection",
        "no ZPP-owned configuration coordination discovery or projection fallback runs",
        "the ZPP command application is installed",
        "a user requests its root and command-group help",
        "init and resolve remain root commands",
        "trait init owns exact repository document initialization",
        "workflow install update and remove remain grouped commands",
        "no flat init-trait install-workflow standalone explain or mirrored space "
        "command exists",
        "a workflow command receives Codex Pi and Codex agent selections in that order",
        "ZPP normalizes the Agent Router agent values",
        "Codex and Pi are selected once in first-requested order",
        "the workflow operation runs once for each selected agent in that order",
        "a multi-agent command requires selection and has an interactive terminal",
        "the user supplies no agent option",
        "ZPP offers Codex Claude Code Pi and Kimi in that order",
        "cancelling the selection performs no mutation",
        "a multi-agent command requires selection without an interactive terminal",
        "ZPP reports that one or more agent values are required",
        "no workflow projection is attempted",
        "resolve may use one invoking agent active artifact context",
        "the user supplies more than one agent option",
        "ZPP rejects the request without combining their artifact contexts",
    )
)
