from behave import given, then, use_step_matcher, when

from features.support import zpp_support as support

given('the packaged ZPP workflow bundle contains all twelve permanent skills')(support.step_packaged_workflow_bundle)

use_step_matcher('parse')
given('no interactive terminal is available')(support.step_noninteractive)
given('an interactive terminal is available')(support.step_interactive)
given('Codex, Pi, and Claude Code have no ZPP integration')(support.step_no_agent_integrations)
then('one selector offers Pi, Codex, and Claude Code')(support.step_selector_offers)
use_step_matcher('re')
given('"(?P<path>C:\\\\missing)" does not exist')(support.step_missing_target)
given('"(?P<path>C:\\\\work\\\\file\\.txt)" is an existing file')(support.step_file_target)
given('"(?P<path>C:\\\\outside)" is an existing directory outside Git')(support.step_outside_git)
use_step_matcher('parse')
given('the current directory is the root of a Git worktree')(support.step_skill_git_root)
given('Codex, Pi, and Claude Code have no local ZPP workflow skills')(support.step_no_local_workflow_skills)
given('every supported agent has no ZPP workflow skills')(support.step_no_local_workflow_skills)
given('Codex, Pi, and Claude Code have no global ZPP workflow skills')(support.step_no_global_workflow_skills)
given('the current project has no authored ZPP layer')(support.step_no_authored_project_layer)
when('the user runs zpp workflow install --local with agents Codex, Pi, and Claude Code')(support.step_install_all_agents_local)
when('the user runs zpp workflow install with agents Codex, Pi, and Claude Code')(support.step_install_all_agents_global)
then('installation succeeds without offering agent selection')(support.step_skill_install_succeeds)
then('one managed bundle is installed in the repository-local Claude Code skill scope')(support.step_local_claude_bundle)
when('the user runs zpp workflow install --global with agent Codex')(support.step_install_global_codex)
when('the user runs zpp workflow install with agent Codex')(support.step_install_default_global_codex)
then('one managed bundle is installed in the repository-local Codex skill scope')(support.step_local_codex_bundle)
then('one managed bundle is installed in the repository-local Pi skill scope under .pi')(support.step_local_pi_bundle)
then('one managed bundle is installed in the user-global Claude Code skill scope')(support.step_global_claude_bundle)
then('one managed bundle is installed in the user-global Codex skill scope')(support.step_global_codex_bundle)
then('one managed bundle is installed in the user-global Pi skill scope under .pi')(support.step_global_pi_bundle)
given('Codex, Pi, and Claude Code have no global OpenSpec operation skills')(support.step_no_global_openspec_skills)
given('Codex, Pi, and Claude Code have no local workflow skills')(support.step_no_local_workflow_integration)
when('the user runs zpp workflow install --local --with-openspec for Codex, Pi, and Claude Code')(support.step_install_all_agents_local_with_openspec)
then('every selected agent has the managed ZPP workflow bundle in its native local skill scope')(support.step_all_local_zpp_bundles)
then('Codex has generated OpenSpec core operation skills under .codex')(support.step_local_codex_openspec)
then('Pi has generated OpenSpec core operation skills under .pi')(support.step_local_pi_openspec)
then('Claude Code has generated OpenSpec core operation skills under .claude')(support.step_local_claude_openspec)
then('every selected agent has its generated OpenSpec core operation skills')(support.step_all_global_openspec_bundles)
then('every selected agent has the current ZPP-managed native lifecycle hooks')(support.step_all_current_native_hooks)
then('both selected agents have the current ZPP-managed native lifecycle hooks')(support.step_selected_current_native_hooks)
then('no repository-local OpenSpec operation skills are installed')(support.step_no_local_openspec_installed)
then('the detected OpenSpec version is recorded for every generated projection')(support.step_global_openspec_versions_recorded)
then('OpenSpec generation used an isolated project beneath the platform temporary directory')(support.step_openspec_generation_boundary_used)
then('the temporary project is removed')(support.step_no_generation_temporary_project)
then('the isolated temporary project is removed')(support.step_no_generation_temporary_project)
then('the current project still has no authored ZPP layer')(support.step_no_authored_layer_after_skills)
then('no authored ZPP layer is created or modified')(support.step_no_authored_layer_after_skills)
then('no repository-local skill scope is changed')(support.step_no_local_skill_scope)
given('"C:\\work\\repo\\nested" is an existing directory inside a Git worktree')(support.step_exact_nested_skill_target)
given('the current directory is outside that worktree')(support.step_current_outside_target_worktree)
when('the user runs zpp workflow install --local "C:\\work\\repo\\nested" with agent Claude Code')(support.step_install_exact_target)
then("the managed bundle is installed only in that exact directory's local Claude Code skill scope")(support.step_only_exact_target)
given('every agent skill scope is recorded')(support.step_record_agent_skill_scopes)
when('the user runs zpp workflow install --local "C:\\missing" with agent Codex')(support.step_install_missing_skill_target)
when('the user runs zpp workflow install --local "C:\\work\\file.txt" with agent Codex')(support.step_install_file_skill_target)
when('the user runs zpp workflow install --local "C:\\outside" with agent Codex')(support.step_install_outside_skill_target)
when('the user runs zpp workflow install "C:\\work\\repo" with agent Codex')(support.step_default_global_with_target)
when('the user runs zpp workflow install with agent Codex and --force')(support.step_global_force_rejected)
when('the user runs zpp workflow install with agent Codex and --with-openspec')(support.step_global_openspec_rejected)
then('the invocation is rejected as a domain error')(support.step_skill_domain_error)
then('the invocation is rejected as a usage error')(support.step_skill_usage_error)
then('every agent skill scope is unchanged')(support.step_agent_skill_scopes_unchanged)
when('the user runs zpp workflow install --local and selects Pi and Claude Code')(support.step_select_skill_agents)
then('the managed bundle is installed in the selected native local scopes')(support.step_selected_skill_scopes)
then('Pi uses its .pi local skill scope')(support.step_pi_uses_local_pi_scope)
then('Codex receives no workflow projection')(support.step_codex_receives_no_projection)
when('the user submits zpp workflow install with no checked agent')(support.step_skill_select_none)
then('installation succeeds without changing any agent skill scope')(support.step_empty_skill_selection)
when('the user cancels zpp workflow install from the agent selector')(support.step_cancel_skill_selection)
then('installation is cancelled without changing any agent skill scope')(support.step_cancelled_skill_selection)
when('the user runs zpp workflow install without an agent option')(support.step_skill_no_agent)
given('Codex has a compatible managed global ZPP workflow bundle')(support.step_compatible_global_codex)
given('Codex has no local ZPP workflow bundle')(support.step_codex_no_local_bundle)
given('Claude Code has no local ZPP workflow bundle')(support.step_claude_no_local_bundle)
when('the user runs zpp workflow install --local with agent Codex')(support.step_install_codex_skill)
then('installation succeeds and reports that the compatible global bundle is reused')(support.step_global_bundle_reused)
then('no local bundle is installed')(support.step_no_local_bundle)
when('the user repeats zpp workflow install --local with agent Codex and --force')(support.step_force_local_codex)
then('a compatible managed local bundle is installed')(support.step_compatible_local_installed)
then('both managed scopes are reported without claiming scope precedence')(support.step_both_scopes_reported)
given('Claude Code has an outdated managed global ZPP workflow bundle')(support.step_outdated_global_claude)
when('the user runs zpp workflow install --local with agent Claude Code')(support.step_install_claude_skill)
then('the current managed bundle is installed locally')(support.step_current_local_claude)
then('the differing managed scope versions are reported without selecting one')(support.step_version_difference_reported)
then('both installations succeed')(support.step_both_skill_installs_succeed)
then('the unrelated files are byte-for-byte unchanged')(support.step_unrelated_skills_unchanged)
then('the unrelated skills are unchanged')(support.step_unrelated_skills_unchanged)
given('Pi has a compatible managed global ZPP workflow bundle under .pi')(support.step_complete_global_pi_bundle)
given('Pi has generated OpenSpec core operation skills for the detected recorded version')(support.step_pi_has_compatible_generated_skills)
given('Pi has the current ZPP-managed native lifecycle hooks')(support.step_pi_has_current_hooks)
given('unrelated files surround every managed projection')(support.step_unrelated_files_surround_complete_pi)
when('the user runs zpp workflow install with agent Pi twice')(support.step_install_complete_pi_twice)
then('every managed projection is byte-for-byte unchanged')(support.step_complete_pi_unchanged)
then('OpenSpec skills are not regenerated')(support.step_openspec_not_regenerated)
given('Pi has no global ZPP integration')(support.step_pi_no_global_integration)
given('Claude Code has an unmanaged global conflict at a required OpenSpec skill destination')(support.step_claude_unmanaged_openspec_conflict)
when('the user runs zpp workflow install with agents Pi and Claude Code')(support.step_install_global_pi_claude)
then("Pi's workflow skills, OpenSpec skills, and native hooks remain unchanged")(support.step_pi_global_integration_unchanged)
given('every selected agent integration is recorded')(support.step_record_selected_integrations)
given("OpenSpec cannot generate one selected agent's core operation skills")(support.step_openspec_generation_fails)
when('the user runs zpp workflow install for those agents')(support.step_install_global_failure_agents)
then('installation fails before committing any selected-agent change')(support.step_generation_failure_rejected)
then('every selected agent integration is byte-for-byte unchanged')(support.step_selected_integrations_unchanged)
given('Codex has an unmanaged local conflict at a required skill destination')(support.step_unmanaged_local_codex_conflict)
when('the user runs zpp workflow install --local with agent Codex and --force')(support.step_force_conflicting_codex)
then('installation fails as a managed-state rejection')(support.step_skill_managed_rejection)
then('update fails as a managed-state rejection')(support.step_skill_managed_rejection)
then('the conflicting Claude Code content is unchanged')(support.step_skill_conflict_unchanged)
then('the conflicting content is unchanged')(support.step_skill_conflict_unchanged)
given('Codex has outdated managed global and forced local ZPP workflow bundles')(support.step_outdated_codex_both_scopes)
when('the user runs zpp workflow update with agent Codex')(support.step_update_global_codex)
then('only the Codex global managed bundle is updated to the packaged version')(support.step_only_codex_global_updated)
then('the forced local Codex bundle is unchanged')(support.step_codex_local_unchanged)
then('every Claude Code scope is unchanged')(support.step_claude_scopes_unchanged)
then('the differing Codex scope versions are reported')(support.step_codex_difference_reported)
given('Codex has a managed global workflow integration')(support.step_codex_complete_global_integration)
given('its OpenSpec projection records the currently detected OpenSpec version')(support.step_projection_records_current_version)
given('the generated OpenSpec skills have distinguishable compatible content')(support.step_record_compatible_openspec_content)
then('the ZPP workflow bundle is updated when needed')(support.step_zpp_bundle_update_succeeds)
then('the generated OpenSpec skills are byte-for-byte unchanged')(support.step_codex_openspec_unchanged)
given('Claude Code has a managed global workflow integration')(support.step_claude_complete_global_integration)
given('its OpenSpec projection records a different version from the detected OpenSpec version')(support.step_claude_projection_version_changes)
then('the OpenSpec core operation skills are regenerated for Claude Code')(support.step_claude_openspec_regenerated)
then('the newly detected OpenSpec version is recorded')(support.step_claude_new_version_recorded)
then('unrelated Claude Code content is byte-for-byte unchanged')(support.step_unrelated_claude_content_unchanged)
given('OpenSpec can generate its core operation skills but cannot report its version')(support.step_openspec_version_unknown)
then('the generated OpenSpec projection records an unknown version')(support.step_unknown_version_recorded)
then('installation otherwise completes normally')(support.step_install_otherwise_normal)
given('Codex has a historical managed global workflow bundle that predates one permanent skill')(support.step_historical_global_codex_bundle)
given('unrelated skills surround the historical managed projection')(support.step_unrelated_historical_global_skills)
then('the Codex global projection contains the complete current workflow bundle')(support.step_historical_global_updated)
then('only paths owned by the historical manifest were replaced')(support.step_only_historical_owned_paths_replaced)
then('the unrelated global skills are byte-for-byte unchanged')(support.step_unrelated_global_skills_unchanged)
when('the user runs zpp workflow update --local with agent Codex')(support.step_update_local_codex)
then('update reports that the local projection is not installed')(support.step_update_reports_local_absent)
then('it does not describe absent local state as unmanaged content')(support.step_absent_is_not_unmanaged)
then('the compatible global bundle remains unchanged')(support.step_compatible_global_bundle_unchanged)
given('Claude Code has an unmanaged global skill directory matching a permanent skill name')(support.step_unmanaged_global_claude_skill)
when('the user runs zpp workflow update with agent Claude Code')(support.step_update_unmanaged_claude)
given('Pi has a managed local ZPP workflow bundle surrounded by unrelated skills')(support.step_managed_pi_with_unrelated)
given('Claude Code has a managed local ZPP workflow bundle')(support.step_managed_local_claude)
given('Pi has generated local OpenSpec operation skills')(support.step_pi_generated_local_openspec)
given('Pi has current ZPP-managed native lifecycle hooks')(support.step_record_pi_current_hooks)
when('the user runs zpp workflow remove --local with agent Pi and declines confirmation')(support.step_decline_skill_remove)
when('the user runs zpp workflow remove --local with agent Pi and --yes')(support.step_confirm_local_skill_remove)
then('only the managed Pi ZPP workflow projection is removed')(support.step_shared_projection_removed)
then("Pi's generated OpenSpec operation skills are unchanged")(support.step_pi_openspec_preserved_on_remove)
then("Pi's native lifecycle hooks are unchanged")(support.step_pi_hooks_preserved_on_remove)
then('the Claude Code projection is unchanged')(support.step_claude_projection_unchanged)
given('Pi has managed global and local ZPP workflow bundles')(support.step_pi_has_global_and_local_bundles)
given('unrelated skills surround both managed projections')(support.step_unrelated_skills_surround_both_pi_projections)
when('the user runs zpp workflow remove with agent Pi and --yes')(support.step_confirm_global_skill_remove)
then('only the managed Pi global ZPP workflow projection is removed')(support.step_only_pi_global_projection_removed)
then('the managed Pi local ZPP workflow projection is unchanged')(support.step_pi_local_projection_unchanged)
given('a participating layer activates a conditionless automatic-workflow trait')(support.step_automatic_workflow_trait)
given('that trait references the permanent workflow skills through skill lookup')(support.step_automatic_trait_lookup)
when('the user resolves traits for the target')(support.step_resolve_automatic_trait)
then('the effective trait directs unattended continuation only across satisfied gates')(support.step_automatic_trait_direction)
then('the skill lookup remains passive frontmatter metadata')(support.step_automatic_lookup_passive)
then('the trait does not grant mutation authority or bypass a failed gate')(support.step_automatic_trait_limits)
when('the user installs the managed bundle for every supported agent')(support.step_install_bundle_for_every_agent)
given('the packaged default profile contains executable-guarded tool-use traits')(support.step_packaged_tool_traits)
then('every native projection contains zpp-use-zmem, zpp-lean-audit, and zpp-author-skill')(support.step_projection_contains_generic_skills)
then('use-zmem looks up zpp-use-zmem and zpp-commit-zmem only when the zmem executable is available')(support.step_use_zmem_guard)
then('zpp-use-zmem teaches recall, search, detail inspection, links, output interpretation, and current-authority verification')(support.step_zmem_skill_complete)
then('zpp-lean-audit is read-only and substantially attributed to the upstream Ponytail ladder, taxonomy, output, and safety boundaries')(support.step_lean_skill_contract)
then("zpp-lean-audit preserves ZPP's proportional maturity evaluation for external dependencies")(support.step_lean_dependency_fit)
then('zpp-author-skill keeps context-continuity and explicit-control-flow guidance in focused references rather than runtime traits')(support.step_author_skill_references)
then('each skill retains its required packaged resources and scripts')(support.step_packaged_resources_retained)
given('a mitigated codespace records its generated project and store branches')(support.step_recorded_reconciliation_branches)
then('every native projection contains the permanent codespace worktree-reconciliation skill')(support.step_projection_contains_reconciliation_skill)
then("the skill consumes the released claim's generated-checkout and branch metadata")(support.step_reconciliation_consumes_metadata)
then('reconciliation requires explicit invocation')(support.step_reconciliation_is_explicit)
then('the skill never makes codespace locking merge work automatically')(support.step_reconciliation_never_auto_merges)
then('successful reconciliation can give every retained branch a disposition before finalization')(support.step_reconciliation_records_disposition)
then('no skill body contains platform, framework, test-runner, or agent-specific policy')(support.step_skill_bodies_neutral)
then('all Python, Django, TypeScript, and Flutter workflow guidance remains in independent optional traits outside the skill bodies')(support.step_platform_guidance_in_optional_traits)
then('automatic-workflow has effective mode "automatic"')(support.step_automatic_mode)
given('the user-owned default profile is recorded')(support.step_record_default_profile)
then('the user-owned default profile is unchanged')(support.step_owned_default_unchanged)
then('completed checkpoints, successful verification, and ordinary stage transitions are not human gates')(support.step_ordinary_transitions_not_gates)
then('the effective trait pauses only for unresolved clarification, a new product boundary, or a missing or changed utility shape')(support.step_only_real_human_gates)
given('a participating layer activates automatic-workflow with mode "manual"')(support.step_manual_automatic_workflow)
given('the user explicitly delegates the complete change end to end')(support.step_complete_delegation)
when('a workflow stage completes with its gate satisfied')(support.step_satisfied_stage)
then('the effective guidance directs continuation through the next owning workflow without requesting stage approval')(support.step_delegated_continuation)
then('the manual configuration remains unchanged')(support.step_manual_config_unchanged)
then('the trait still cannot execute a skill or grant mutation authority')(support.step_manual_trait_advisory)
given('the initialized default profile contains the platform-neutral base traits')(support.step_initialized_default_traits)
then('cross-cutting codespace claim, zero-assumption, and Ponytail guidance remains in its owning trait')(support.step_cross_cutting_trait_ownership)
given('a participating layer activates codespace-claim-guard')(support.step_activate_claim_guard)
given('automatic-workflow has effective mode "automatic"')(support.step_claim_workflow_automatic)
given('automatic-workflow has effective mode "manual"')(support.step_claim_workflow_manual)
when('a write-capable ZPP workflow is about to mutate a physical checkout')(support.step_claim_guard_before_mutation)
then('the claim guard directs automatic acquisition or verification of the claim')(support.step_claim_guard_automatic)
then('the claim guard directs prompting before claim acquisition')(support.step_claim_guard_manual)
then('the trait does not treat an OpenSpec workset as ownership')(support.step_claim_guard_not_workset_authority)
then('the trait rejects supported direct writes into associated read-only members')(support.step_claim_guard_rejects_read_only_writes)
then('the trait cannot override a conflicting claim or grant mutation authority')(support.step_claim_guard_is_advisory)
then('each permanent skill contains only its stage-specific operations and gates')(support.step_skills_stage_specific)
then('hard OpenSpec operation ownership, verification authority, and zmem materiality remain in their owning skills')(support.step_hard_rules_remain_in_skills)
given('a workflow relates a product change, a utility companion, and a temporary internal anchor')(support.step_related_change_types)
given('an unrelated OpenSpec change remains active')(support.step_unrelated_change_active)
when('the mature workflow reaches finalization')(support.step_workflow_reaches_finalization)
then('the product change is handed to the owning OpenSpec finalizer')(support.step_product_change_finalized)
then('the verified utility companion and consumed internal anchor are discarded')(support.step_companions_discarded)
then('the unrelated active change is left untouched')(support.step_unrelated_change_untouched)
then('completion requires a final audit of the related change set')(support.step_final_related_change_audit)
given('a mature product change has formed and checkpointed canonical specifications')(support.step_mature_change_has_formed_specs)
given('its active OpenSpec proposal and capability deltas remain uncommitted')(support.step_active_openspec_remains_uncommitted)
when('the owning OpenSpec finalizer archives the product change')(support.step_openspec_finalizer_archives)
then('the exact finalized archive is handed to zpp-commit-zmem as material repository history')(support.step_archive_becomes_repository_history)
then('the archive checkpoint excludes unrelated active changes and disposable utility plans')(support.step_archive_checkpoint_is_scoped)
then('archiving alone does not require a zmem annotation')(support.step_archive_does_not_force_zmem)
then('the repository ignore policy keeps active changes hidden and finalized archives trackable')(support.step_repository_ignore_policy_distinguishes_archives)
given('a consumed related OpenSpec change remains active without an owning stage')(support.step_unowned_related_change)
when('the workflow evaluates its completion gate')(support.step_evaluate_completion_gate)
then('the workflow cannot report completion')(support.step_completion_blocked)
then('the unrelated OpenSpec change list is not required to be empty')(support.step_unrelated_list_may_remain_active)
given('canonical OpenSpec records the currently accepted product behavior')(support.step_canonical_openspec_current)
given('zmem records chronological decisions including a later change of direction')(support.step_zmem_temporal_decisions)
given('an active OpenSpec change contains mutable proposal and capability delta specs')(support.step_active_planning_artifacts)
when('clarification establishes the product boundary')(support.step_clarification_establishes_boundary)
then('it compares the later zmem direction with canonical OpenSpec')(support.step_clarification_compares_history)
then('it treats canonical OpenSpec as the long-standing current authority')(support.step_canonical_authority)
then('it treats zmem as temporal decision history rather than current product truth')(support.step_zmem_temporal_not_current)
then('it treats the active OpenSpec planning artifacts as temporary working state')(support.step_planning_artifacts_temporary_working_state)
then('no zmem dependency graph is required')(support.step_no_zmem_dependency_graph)
given('an OpenSpec proposal declares multiple new or modified capabilities')(support.step_proposal_declares_capabilities)
when('clarification settles behavior for the complete change')(support.step_clarification_settles_complete_change)
then('proposal.md retains the overview, capability inventory, impact, and unresolved owner decisions')(support.step_proposal_retains_overview)
then('each declared capability has its own specs capability delta document')(support.step_each_capability_has_delta)
then('settled behavior is persisted into its owning delta before clarification continues')(support.step_settled_behavior_persisted)
then('design and task artifacts follow the selected OpenSpec schema rather than a ZPP one-file rule')(support.step_schema_owns_other_artifacts)
given('a confirmed OpenSpec change contains proposal and capability delta documents')(support.step_confirmed_multi_artifact_change)
when('the workflow shapes the complete Gherkin feature set')(support.step_shape_complete_gherkin)
then('shaping consumes both proposal and capability delta documents')(support.step_shaping_consumes_artifacts)
then('shaping removes only executable examples duplicated by Gherkin')(support.step_shaping_removes_only_examples)
then('shaping preserves stable intent, constraints, invariants, and acceptance obligations')(support.step_shaping_preserves_contract)
when('mature green behavior later forms canonical specifications')(support.step_mature_green_forms_specs)
then('formation reconciles the existing capability deltas')(support.step_formation_reconciles_deltas)
then('formation does not create capability specifications for the first time')(support.step_formation_requires_existing_deltas)
given('a valid conventional commit message contains no zmem annotation')(support.step_unannotated_conventional_message)
when('the bundled commit-message validator checks an ordinary commit')(support.step_validate_ordinary_commit)
then('validation succeeds with zero zmem annotations')(support.step_ordinary_commit_valid)
when('the bundled commit-message validator checks a memory-bearing checkpoint')(support.step_validate_memory_checkpoint)
then('validation fails because a canonical zmem annotation is required')(support.step_memory_checkpoint_requires_annotation)
given('mature green behavior reflects the latest accepted decision')(support.step_green_behavior_latest_decision)
given('zmem retains earlier directions, reversals, and their reasons')(support.step_zmem_retains_history)
when('the workflow forms canonical OpenSpec specifications')(support.step_form_canonical_specs)
then('only the enduring current behavior enters canonical OpenSpec')(support.step_only_current_behavior_is_canonical)
then('abandoned or superseded chronology remains in zmem')(support.step_superseded_chronology_in_zmem)
then('no zmem checkpoint is created merely to mark specification formation')(support.step_no_spec_marker_zmem)
