from behave import given, then, when

from features.support import update_support as update
from features.support import zpp_support as support


given("valid initialized user state")(support.step_initialized)
given("Pi has an outdated managed global ZPP workflow bundle under .pi with no OpenSpec projection")(update.install_outdated_pi_without_openspec)
given("Codex has a compatible managed global ZPP workflow bundle with a historical native hook")(update.install_current_codex_with_historical_hook)
given("Claude Code has no managed global ZPP workflow bundle")(update.assert_no_claude_workflow)
given("unrelated files surround every agent surface")(update.surround_global_surfaces)
when("the user runs zpp update")(update.run_update)
then("Pi and Codex contain the complete current twelve-skill workflow bundle")(update.assert_pi_codex_workflows_current)
then("Pi receives generated OpenSpec core operation skills for the detected version")(update.assert_pi_openspec_generated)
then("both installed workflows have the current ZPP-managed native lifecycle hooks")(update.assert_installed_hooks_current)
then("Claude Code receives no workflow, OpenSpec skill, or native hook")(update.assert_claude_untouched)
then("every unrelated file is byte-for-byte unchanged")(update.assert_unrelated_global_unchanged)
given("Pi and Claude Code have managed global workflow integrations")(update.install_pi_claude_integrations)
given("Pi's OpenSpec projection records the currently detected version with distinguishable content")(update.record_pi_current_projection)
given("Claude Code's OpenSpec projection records a different version")(update.make_claude_projection_outdated)
then("Pi's generated OpenSpec skills are byte-for-byte unchanged")(update.assert_pi_openspec_unchanged)
then("Claude Code's OpenSpec core operation skills are regenerated")(update.assert_claude_openspec_regenerated)
then("Claude Code records the newly detected OpenSpec version")(update.assert_claude_detected_version)
then("both ZPP workflow bundles are current")(update.assert_pi_claude_workflows_current)
given("valid initialized user state whose default profile is missing one packaged entry")(update.initialize_with_missing_default)
given("Pi has an outdated managed global workflow integration")(update.install_outdated_pi_integration)
given("Claude Code has modified content inside its managed global workflow projection")(update.create_modified_claude_workflow)
given("every included global surface is recorded")(update.record_included_global_surfaces)
then("update fails as a managed-state rejection identifying Claude Code")(update.assert_conflict_identifies_claude)
then("the persistent default profile remains unchanged")(update.assert_default_unchanged_after_conflict)
then("every included hook, workflow bundle, and OpenSpec projection is byte-for-byte unchanged")(update.assert_included_global_unchanged)
given("every supported agent has a complete compatible managed global workflow integration")(update.install_all_global_integrations)
given("their generated OpenSpec projections record the detected version")(update.assert_all_openspec_current)
given("the persistent default profile contains every packaged standard entry")(update.assert_default_complete)
given("compatible and conflicting repository-local workflow projections are recorded")(update.create_local_compatible_and_conflicting_projections)
when("the user runs zpp update twice")(update.run_update_twice)
then("both updates succeed without rewriting any managed or authored global content")(update.assert_two_updates_no_rewrite)
then("no OpenSpec projection is regenerated")(update.assert_no_openspec_regeneration)
then("every repository-local workflow projection is byte-for-byte unchanged")(update.assert_local_projections_unchanged)
