from features.support.bindings import register_exact_steps

register_exact_steps(
    (
        "a first-win family has matching repository space and global flavors",
        "ZPP resolves the family",
        "only the first repository flavor is retained",
        "its complete body is returned",
        "no flavor directly matches a first-win family",
        "the first compatible Flutter flavor has successful workspace evidence",
        "the Flutter flavor is retained",
        "later evidence flavors are not considered as winners",
        "its missing Flutter facet is backfilled without restarting resolution",
        "an all family has one direct match and two compatible evidence-backed matches",
        "all three flavors are retained in effective order",
        "their complete bodies are returned in that order",
        "an extend family has generic Python, Python with uv, and Flutter flavors",
        "the known context contains Python Flutter and uv",
        "Python with uv and Flutter are retained in effective order",
        "generic Python is removed as dominated",
        "an extend family matches Python with uv and Python with Click flavors",
        "both complete flavors are retained",
        "neither facet constraint set contains the other",
        "compatible selected evidence flavors derive Python and Flutter",
        "language was not already known",
        "ZPP backfills the resolution context",
        "language contains Python followed by Flutter without duplicates",
        "resolution does not run again",
        "invocation context repository context and stored context provide facet values",
        "ZPP builds the known resolution context",
        "invocation values take precedence over repository values",
        "repository values take precedence over stored and evidence-derived values",
        "a conflicting evidence flavor is excluded",
        "ZPP_CONTEXT carries facets provenance target identity and evidence "
        "fingerprints",
        "its target differs from the selected repository",
        "the stored context is ignored",
        "evidence used by a stored value has changed",
        "that evidence-derived value is invalidated",
        "a flavor checks a root-anchored workspace path literal file content and uv "
        "availability",
        "ZPP evaluates its evidence against the selected target",
        "the anchored path cannot match a nested substitute",
        "file content is compared literally in the named file",
        "the result records has_uv as a boolean",
        "a resolution contains rejected dominated and evidence-selected flavors",
        "a user requests its explanation",
        "the explanation identifies context source order policy decisions and evidence",
        "it identifies retained flavors backfilled facets and source provenance",
        "the resolved bodies remain unchanged",
        "no flavor directly matches or has successful compatible evidence",
        "the family contributes no body",
        "a manual family has a flavor with successful activation evidence",
        "ZPP resolves all commonly active families",
        "the manual family contributes no body",
        "a manual family has one matching flavor and one unmatched flavor",
        "a user resolves that family directly",
        "only the normally selected matching flavor contributes its complete body",
        "unrelated always-run families do not contribute",
        "a manual family has no matching facet or evidence flavor",
        "the requested family contributes no body",
        "several known trait families are available",
        "a user requests two families and repeats the first family",
        "each requested family is considered once in first-requested order",
        "an always-run family is available",
        "a user directly requests an unknown family",
        "resolution fails visibly",
        "the unrelated always-run family contributes no body",
        "an always-run extend family has generic Python Python with uv and Flutter "
        "flavors",
        "no flavor has matching context or evidence",
        "bypass-selected facets do not backfill the context",
        "resolution retains several complete trait bodies",
        "a user resolves without explanation",
        "standard output contains only those complete bodies in deterministic order",
        "no diagnostic envelope is emitted",
        "resolution retains several complete trait bodies and recomputes stored "
        "context",
        "a user resolves with explanation",
        "structured output contains the same bodies effective context and "
        "deterministic decisions",
    )
)
