from features.support.bindings import register_exact_steps

register_exact_steps(
    (
        "ZPP is installed for a supported agent",
        "Agent Router projects the workflow integration",
        "one consolidated ZPP workflow skill is installed",
        "no ZPP 1.x stage skill is required",
        "the packaged workflow skill and trait source are available",
        "a user inspects their distributed contents",
        "workflow stages transitions gates and authority exist in the skill",
        "no workflow trait family is packaged",
        "ZPP packages its standard TOML traits under artifacts traits",
        "a user inspects the packaged family inventory",
        "BDD operation structure and execution remain separate focused families",
        "TDD build dependency tooling and zero-assumption behavior remain represented",
        "no lease conflict or reconciliation policy family is packaged",
        "the packaged source path is not imposed as the runtime collection path",
        "the packaged BDD execution modes are available",
        "a repository resolves its BDD execution policy",
        "manual disabled complete targeted and targeted-default behavior comes from "
        "bdd-execution",
        "no bdd-workflow compatibility family is packaged",
        "the packaged zero-assumptions and tooling families are available",
        "a user inspects their activation and flavors",
        "zero-assumptions declares always-run activation",
        "tooling contains evidence-backed rg and jq guidance without zmem workflow "
        "policy",
        "a workflow encounters an OpenLease conflict or final reconciliation",
        "ZPP determines the governing behavior",
        "OpenLease or the consolidated workflow skill supplies the operational "
        "contract",
        "no packaged trait is treated as lease or reconciliation authority",
        "a workflow invocation has repository files stored context and resolved traits",
        "the invocation does not identify a stage",
        "the consolidated skill requests the stage",
        "it does not infer a stage from those inputs",
        "the native ZPP hook injected several complete contextual trait bodies",
        "the consolidated skill applies those bodies in injected order",
        "the bodies may specialize repository language framework test and build "
        "guidance",
        "they cannot authorize mutation advance a stage or establish completion",
        "the packaged consolidated workflow skill is available",
        "a user inspects its workflow instructions",
        "the skill does not instruct the agent to run trait resolution",
        "the skill does not instruct the agent to publish ZPP_CONTEXT",
        "the user authorized end-to-end workflow progression",
        "the current stage has independently verified completion",
        "the workflow continues",
        "it invokes the next stage as a distinct explicit action",
        "it does not delegate stage choice to the trait hook",
        "a workflow stage requires OpenSpec OpenLease and Agent Router operations",
        "the consolidated skill dispatches those operations",
        "it follows the installed skill that owns each OpenSpec operation",
        "uses OpenLease only for its public coordination and configuration contracts",
        "uses Agent Router only for its public discovery and projection contracts",
        "a machine retains one or more ZPP 1.x workflow skills",
        "ZPP 2.0 runs its workflow",
        "it does not invoke translate or treat them as migration sources",
    )
)
