from behave import given, then, use_step_matcher, when

from features.support import zpp_support as support

given('an explicit workspace descriptor names committed project checkouts')(support.bind_claim_step(support.claim_given, 'an explicit workspace descriptor names committed project checkouts'))
given('an explicit path list names committed project checkouts')(support.bind_claim_step(support.claim_given, 'an explicit path list names committed project checkouts'))
given('one project uses a repo-local OpenSpec root')(support.bind_claim_step(support.claim_given, 'one project uses a repo-local OpenSpec root'))
given('another project resolves to an external writable OpenSpec store')(support.bind_claim_step(support.claim_given, 'another project resolves to an external writable OpenSpec store'))
given('the projects also use a registered store only as a reference')(support.bind_claim_step(support.claim_given, 'the projects also use a registered store only as a reference'))
given('no active codespace claims any resolved physical checkout')(support.bind_claim_step(support.claim_given, 'no active codespace claims any resolved physical checkout'))
given('the current directory is inside a checkout claimed by one active ZPP codespace')(support.bind_claim_step(support.claim_given, 'the current directory is inside a checkout claimed by one active ZPP codespace'))
given('instead no active claim or explicit input supplies writable targets')(support.bind_claim_step(support.claim_given, 'instead no active claim or explicit input supplies writable targets'))
given('two ZPP processes on the same machine request claims containing the same physical checkout')(support.bind_claim_step(support.claim_given, 'two ZPP processes on the same machine request claims containing the same physical checkout'))
given('an active codespace records the full starting commit hashes of its claimed checkouts')(support.bind_claim_step(support.claim_given, 'an active codespace records the full starting commit hashes of its claimed checkouts'))
given('one claimed checkout later receives file changes and new commits')(support.bind_claim_step(support.claim_given, 'one claimed checkout later receives file changes and new commits'))
given('a requested repository has no first commit')(support.bind_claim_step(support.claim_given, 'a requested repository has no first commit'))
given('an associated store is neither writable nor reference-only')(support.bind_claim_step(support.claim_given, 'an associated store is neither writable nor reference-only'))
given('all codespace claim and optional workset state is recorded')(support.bind_claim_step(support.claim_given, 'all codespace claim and optional workset state is recorded'))
given('one codespace claims Project A, Project B, and writable Store 1')(support.bind_claim_step(support.claim_given, 'one codespace claims Project A, Project B, and writable Store 1'))
given('another request contains uncontested Project C, the claimed Project B checkout, and Store 1')(support.bind_claim_step(support.claim_given, 'another request contains uncontested Project C, the claimed Project B checkout, and Store 1'))
given('the claimed Project B checkout has advanced to a new commit')(support.bind_claim_step(support.claim_given, 'the claimed Project B checkout has advanced to a new commit'))
given('a requested codespace conflicts with an active codespace')(support.bind_claim_step(support.claim_given, 'a requested codespace conflicts with an active codespace'))
given('the complete project, store, optional workset, and claim state is recorded')(support.bind_claim_step(support.claim_given, 'the complete project, store, optional workset, and claim state is recorded'))
given('another request contains uncontested Project C, Project B, and Store 1')(support.bind_claim_step(support.claim_given, 'another request contains uncontested Project C, Project B, and Store 1'))
given('the requested codespace begins from the same starting commits as the active codespace')(support.bind_claim_step(support.claim_given, 'the requested codespace begins from the same starting commits as the active codespace'))
given('mitigation would use a sibling path or branch that already exists')(support.bind_claim_step(support.claim_given, 'mitigation would use a sibling path or branch that already exists'))
given('the complete original codespace state is recorded')(support.bind_claim_step(support.claim_given, 'the complete original codespace state is recorded'))
given('a mitigated codespace maps original logical store ids to isolated store checkouts')(support.bind_claim_step(support.claim_given, 'a mitigated codespace maps original logical store ids to isolated store checkouts'))
given('an unrelated user-owned OpenSpec workset exists')(support.bind_claim_step(support.claim_given, 'an unrelated user-owned OpenSpec workset exists'))
given('a released codespace has a clean generated worktree and a dirty generated worktree')(support.bind_claim_step(support.claim_given, 'a released codespace has a clean generated worktree and a dirty generated worktree'))
given('a durable codespace claim was abandoned without being unlocked')(support.bind_claim_step(support.claim_given, 'a durable codespace claim was abandoned without being unlocked'))
given('its generated worktrees may contain dirty files')(support.bind_claim_step(support.claim_given, 'its generated worktrees may contain dirty files'))
given('orphaned ZPP-owned projections and unrelated user-owned worksets exist')(support.bind_claim_step(support.claim_given, 'orphaned ZPP-owned projections and unrelated user-owned worksets exist'))
given('a ZPP-owned workset projection is absent from the durable active codespace index')(support.bind_claim_step(support.claim_given, 'a ZPP-owned workset projection is absent from the durable active codespace index'))
given('user-owned worksets, branches, and worktrees also exist')(support.bind_claim_step(support.claim_given, 'user-owned worksets, branches, and worktrees also exist'))
given('codespaces have previously used many different target combinations')(support.bind_claim_step(support.claim_given, 'codespaces have previously used many different target combinations'))
given('every released generated checkout and branch has received a final disposition')(support.bind_claim_step(support.claim_given, 'every released generated checkout and branch has received a final disposition'))
given('a mitigated codespace records every generated project and store branch')(support.bind_claim_step(support.claim_given, 'a mitigated codespace records every generated project and store branch'))
given('explicit writable paths and explicit read-only repository paths have committed heads')(support.bind_claim_step(support.claim_given, 'explicit writable paths and explicit read-only repository paths have committed heads'))
given('a read-only repository resolves external OpenSpec stores')(support.bind_claim_step(support.claim_given, 'a read-only repository resolves external OpenSpec stores'))
given('another active codespace already claims one selected read-only repository')(support.bind_claim_step(support.claim_given, 'another active codespace already claims one selected read-only repository'))
given('the current directory belongs only to a read-only member of one or more codespaces')(support.bind_claim_step(support.claim_given, 'the current directory belongs only to a read-only member of one or more codespaces'))
given('a selected read-only repository has no first commit')(support.bind_claim_step(support.claim_given, 'a selected read-only repository has no first commit'))
given('a prepared codespace with writable and read-only members has no OpenSpec workset projection')(support.bind_claim_step(support.claim_given, 'a prepared codespace with writable and read-only members has no OpenSpec workset projection'))
given('an active codespace contains committed writable and read-only members')(support.bind_claim_step(support.claim_given, 'an active codespace contains committed writable and read-only members'))
given('an active codespace has a durable mixed-access shape and may have one optional projection')(support.bind_claim_step(support.claim_given, 'an active codespace has a durable mixed-access shape and may have one optional projection'))
given('a shape-changing edit targets an active codespace without --yes or -y')(support.bind_claim_step(support.claim_given, 'a shape-changing edit targets an active codespace without --yes or -y'))
given('instead the user declines either confirmation')(support.bind_claim_step(support.claim_given, 'instead the user declines either confirmation'))
given('a shape-changing edit targets an active codespace')(support.bind_claim_step(support.claim_given, 'a shape-changing edit targets an active codespace'))
given('an edit contains contradictory operations or cannot complete validation, mitigation, or replacement')(support.bind_claim_step(support.claim_given, 'an edit contains contradictory operations or cannot complete validation, mitigation, or replacement'))
given('an edit produces the existing effective membership, roles, and paths')(support.bind_claim_step(support.claim_given, 'an edit produces the existing effective membership, roles, and paths'))
given('an active codespace contains retained, removed, and demoted generated writable members')(support.bind_claim_step(support.claim_given, 'an active codespace contains retained, removed, and demoted generated writable members'))
given('an active codespace has writable and read-only physical checkout targets and a durable claim')(support.bind_claim_step(support.claim_given, 'an active codespace has writable and read-only physical checkout targets and a durable claim'))
given('an agent is associated with a codespace containing a read-only repository')(support.bind_claim_step(support.claim_given, 'an agent is associated with a codespace containing a read-only repository'))
when('the user runs zpp codespace lock using an explicit workspace descriptor')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace lock using an explicit workspace descriptor'))
when('the user runs zpp codespace lock using an explicit path list')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace lock using an explicit path list'))
when('the user runs zpp codespace lock without paths')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace lock without paths'))
when('the user repeats locking with an explicit workspace descriptor or path list')(support.bind_claim_step(support.claim_when, 'the user repeats locking with an explicit workspace descriptor or path list'))
when('both attempt to acquire their complete target sets concurrently')(support.bind_claim_step(support.claim_when, 'both attempt to acquire their complete target sets concurrently'))
when('ZPP inspects or re-locks the same effective target set')(support.bind_claim_step(support.claim_when, 'ZPP inspects or re-locks the same effective target set'))
when('the user attempts to lock the requested target set')(support.bind_claim_step(support.claim_when, 'the user attempts to lock the requested target set'))
when('the user declines the grouped mitigation offer')(support.bind_claim_step(support.claim_when, 'the user declines the grouped mitigation offer'))
when('the user confirms conflict mitigation')(support.bind_claim_step(support.claim_when, 'the user confirms conflict mitigation'))
when('the user confirms mitigation')(support.bind_claim_step(support.claim_when, 'the user confirms mitigation'))
when('the user declines the offer to open it')(support.bind_claim_step(support.claim_when, 'the user declines the offer to open it'))
when('the user later runs zpp codespace open for the prepared codespace')(support.bind_claim_step(support.claim_when, 'the user later runs zpp codespace open for the prepared codespace'))
when('the codespace membership or effective paths later change')(support.bind_claim_step(support.claim_when, 'the codespace membership or effective paths later change'))
when('the user runs zpp codespace activate for that codespace')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace activate for that codespace'))
when('the user runs zpp codespace exec for that codespace with an OpenSpec command')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace exec for that codespace with an OpenSpec command'))
when('the user runs zpp codespace list and zpp codespace status')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace list and zpp codespace status'))
when('the user runs zpp codespace unlock for the active codespace')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace unlock for the active codespace'))
when('the user runs zpp codespace cleanup')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace cleanup'))
when('every retained branch is reconciled or explicitly abandoned and generated worktrees are gone')(support.bind_claim_step(support.claim_when, 'every retained branch is reconciled or explicitly abandoned and generated worktrees are gone'))
when('the reconciliation workflow or user runs zpp codespace finalize')(support.bind_claim_step(support.claim_when, 'the reconciliation workflow or user runs zpp codespace finalize'))
when('the user explicitly confirms forced recovery')(support.bind_claim_step(support.claim_when, 'the user explicitly confirms forced recovery'))
when('the user runs any mutating zpp codespace command')(support.bind_claim_step(support.claim_when, 'the user runs any mutating zpp codespace command'))
when('those released codespaces are finalized')(support.bind_claim_step(support.claim_when, 'those released codespaces are finalized'))
when('the user runs zpp codespace lock with the writable paths and --read-only paths')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace lock with the writable paths and --read-only paths'))
when('the user runs a codespace command without an identity or activated environment')(support.bind_claim_step(support.claim_when, 'the user runs a codespace command without an identity or activated environment'))
when('the user runs zpp codespace edit with --add for a committed path and --yes')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace edit with --add for a committed path and --yes'))
when('the user runs zpp codespace edit with --add-read-only for a committed path and --yes')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace edit with --add-read-only for a committed path and --yes'))
when('the user runs zpp codespace edit with --remove for a committed path and --yes')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace edit with --remove for a committed path and --yes'))
when('the user runs zpp codespace edit with --promote for a committed path and --yes')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace edit with --promote for a committed path and --yes'))
when('the user runs zpp codespace edit with --demote for a committed path and --yes')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace edit with --demote for a committed path and --yes'))
when('one valid edit changes several members and access roles')(support.bind_claim_step(support.claim_when, 'one valid edit changes several members and access roles'))
when('the user accepts the complete successor shape')(support.bind_claim_step(support.claim_when, 'the user accepts the complete successor shape'))
when('the user accepts the release confirmation')(support.bind_claim_step(support.claim_when, 'the user accepts the release confirmation'))
when('the user runs zpp codespace edit with --yes or -y')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace edit with --yes or -y'))
when('the user attempts the edit')(support.bind_claim_step(support.claim_when, 'the user attempts the edit'))
when('the user runs zpp codespace edit')(support.bind_claim_step(support.claim_when, 'the user runs zpp codespace edit'))
when('the user confirms the shape edit')(support.bind_claim_step(support.claim_when, 'the user confirms the shape edit'))
when('the user locks, edits, opens, unlocks, cleans, recovers, or finalizes that codespace')(support.bind_claim_step(support.claim_when, 'the user locks, edits, opens, unlocks, cleans, recovers, or finalizes that codespace'))
when('a supported direct edit or write targets that read-only repository')(support.bind_claim_step(support.claim_when, 'a supported direct edit or write targets that read-only repository'))
then('one durable codespace claim owns every complete project checkout exactly once')(support.bind_claim_step(support.claim_then, 'one durable codespace claim owns every complete project checkout exactly once'))
then('the claim also owns the external writable store checkout exactly once')(support.bind_claim_step(support.claim_then, 'the claim also owns the external writable store checkout exactly once'))
then('the repo-local OpenSpec root is covered by its containing project checkout')(support.bind_claim_step(support.claim_then, 'the repo-local OpenSpec root is covered by its containing project checkout'))
then('the reference-only store remains shared and unclaimed')(support.bind_claim_step(support.claim_then, 'the reference-only store remains shared and unclaimed'))
then("the claim records each target's full starting commit hash")(support.bind_claim_step(support.claim_then, "the claim records each target's full starting commit hash"))
then('no Git worktree or OpenSpec workset is created')(support.bind_claim_step(support.claim_then, 'no Git worktree or OpenSpec workset is created'))
then('no editor or agent is opened')(support.bind_claim_step(support.claim_then, 'no editor or agent is opened'))
then('ZPP identifies the existing codespace')(support.bind_claim_step(support.claim_then, 'ZPP identifies the existing codespace'))
then('no second claim or OpenSpec workset is created')(support.bind_claim_step(support.claim_then, 'no second claim or OpenSpec workset is created'))
then('locking is rejected without inferring ownership from an OpenSpec workset')(support.bind_claim_step(support.claim_then, 'locking is rejected without inferring ownership from an OpenSpec workset'))
then('locking does not guess the folders open in an editor')(support.bind_claim_step(support.claim_then, 'locking does not guess the folders open in an editor'))
then('ZPP resolves the explicitly requested writable targets')(support.bind_claim_step(support.claim_then, 'ZPP resolves the explicitly requested writable targets'))
then('exactly one complete codespace claim becomes active')(support.bind_claim_step(support.claim_then, 'exactly one complete codespace claim becomes active'))
then('the other request reports the active owner of the conflicting checkout')(support.bind_claim_step(support.claim_then, 'the other request reports the active owner of the conflicting checkout'))
then('no partial claim remains from the rejected request')(support.bind_claim_step(support.claim_then, 'no partial claim remains from the rejected request'))
then('the existing codespace remains active')(support.bind_claim_step(support.claim_then, 'the existing codespace remains active'))
then('its starting commit hashes remain unchanged')(support.bind_claim_step(support.claim_then, 'its starting commit hashes remain unchanged'))
then('no claim or optional workset generation is replaced because of commit movement')(support.bind_claim_step(support.claim_then, 'no claim or optional workset generation is replaced because of commit movement'))
then('current dirty and commit state is reported separately')(support.bind_claim_step(support.claim_then, 'current dirty and commit state is reported separately'))
then('locking is rejected with the unresolved target identified')(support.bind_claim_step(support.claim_then, 'locking is rejected with the unresolved target identified'))
then('all recorded codespace claim and optional workset state is unchanged')(support.bind_claim_step(support.claim_then, 'all recorded codespace claim and optional workset state is unchanged'))
then('the conflict report includes Project B and Store 1 together')(support.bind_claim_step(support.claim_then, 'the conflict report includes Project B and Store 1 together'))
then('Project B remains conflicting despite its changed current commit')(support.bind_claim_step(support.claim_then, 'Project B remains conflicting despite its changed current commit'))
then('Project C is not reported as conflicting')(support.bind_claim_step(support.claim_then, 'Project C is not reported as conflicting'))
then('no mitigation occurs before the user confirms it')(support.bind_claim_step(support.claim_then, 'no mitigation occurs before the user confirms it'))
then('no worktree, branch, claim, or OpenSpec workset is created')(support.bind_claim_step(support.claim_then, 'no worktree, branch, claim, or OpenSpec workset is created'))
then('the complete recorded state is unchanged')(support.bind_claim_step(support.claim_then, 'the complete recorded state is unchanged'))
then('Project C continues using its canonical checkout')(support.bind_claim_step(support.claim_then, 'Project C continues using its canonical checkout'))
then('Project B and Store 1 receive distinct sibling worktrees named from the new codespace instance')(support.bind_claim_step(support.claim_then, 'Project B and Store 1 receive distinct sibling worktrees named from the new codespace instance'))
then("each generated worktree branches from its target's recorded starting commit")(support.bind_claim_step(support.claim_then, "each generated worktree branches from its target's recorded starting commit"))
then('no uncommitted content is copied into a generated worktree')(support.bind_claim_step(support.claim_then, 'no uncommitted content is copied into a generated worktree'))
then('the mitigated codespace claims the isolated physical checkouts')(support.bind_claim_step(support.claim_then, 'the mitigated codespace claims the isolated physical checkouts'))
then('its private OpenSpec registry maps the original Store 1 id to the isolated Store 1 checkout')(support.bind_claim_step(support.claim_then, 'its private OpenSpec registry maps the original Store 1 id to the isolated Store 1 checkout'))
then('the shared global OpenSpec registry is unchanged')(support.bind_claim_step(support.claim_then, 'the shared global OpenSpec registry is unchanged'))
then('no OpenSpec workset is created until opening is requested')(support.bind_claim_step(support.claim_then, 'no OpenSpec workset is created until opening is requested'))
then('ZPP offers to open the prepared codespace without changing the existing workspace')(support.bind_claim_step(support.claim_then, 'ZPP offers to open the prepared codespace without changing the existing workspace'))
then('the prepared codespace and its claim remain available without a projection')(support.bind_claim_step(support.claim_then, 'the prepared codespace and its claim remain available without a projection'))
then('the current editor or agent remains unchanged')(support.bind_claim_step(support.claim_then, 'the current editor or agent remains unchanged'))
then('ZPP creates and opens one owned projection named `zpp-<instance>-g<generation>`')(support.bind_claim_step(support.claim_then, 'ZPP creates and opens one owned projection named `zpp-<instance>-g<generation>`'))
then('repeated opening reuses that projection while its effective paths are unchanged')(support.bind_claim_step(support.claim_then, 'repeated opening reuses that projection while its effective paths are unchanged'))
then('opening replaces the projection with the next structural generation')(support.bind_claim_step(support.claim_then, 'opening replaces the projection with the next structural generation'))
then('the superseded ZPP-owned projection is removed')(support.bind_claim_step(support.claim_then, 'the superseded ZPP-owned projection is removed'))
then('mitigation is rejected without reusing or overwriting the existing path or branch')(support.bind_claim_step(support.claim_then, 'mitigation is rejected without reusing or overwriting the existing path or branch'))
then("the resulting shell uses the codespace's private OpenSpec registry")(support.bind_claim_step(support.claim_then, "the resulting shell uses the codespace's private OpenSpec registry"))
then('that command uses the same private OpenSpec registry')(support.bind_claim_step(support.claim_then, 'that command uses the same private OpenSpec registry'))
then('both paths preserve the original logical store ids')(support.bind_claim_step(support.claim_then, 'both paths preserve the original logical store ids'))
then('neither path changes shared global OpenSpec registration')(support.bind_claim_step(support.claim_then, 'neither path changes shared global OpenSpec registration'))
then('its write ownership and optional ZPP-owned projection are removed')(support.bind_claim_step(support.claim_then, 'its write ownership and optional ZPP-owned projection are removed'))
then('every project and store worktree is preserved')(support.bind_claim_step(support.claim_then, 'every project and store worktree is preserved'))
then('only outstanding generated-checkout and branch reconciliation debt is retained')(support.bind_claim_step(support.claim_then, 'only outstanding generated-checkout and branch reconciliation debt is retained'))
then('the unrelated user-owned OpenSpec workset is unchanged')(support.bind_claim_step(support.claim_then, 'the unrelated user-owned OpenSpec workset is unchanged'))
then('only the clean ZPP-owned generated worktree is removed')(support.bind_claim_step(support.claim_then, 'only the clean ZPP-owned generated worktree is removed'))
then('the dirty generated worktree and all of its content are preserved')(support.bind_claim_step(support.claim_then, 'the dirty generated worktree and all of its content are preserved'))
then('no canonical checkout or user-owned worktree is removed')(support.bind_claim_step(support.claim_then, 'no canonical checkout or user-owned worktree is removed'))
then('the released record is removed')(support.bind_claim_step(support.claim_then, 'the released record is removed'))
then('the abandoned claim and its orphaned ZPP-owned projections are removed')(support.bind_claim_step(support.claim_then, 'the abandoned claim and its orphaned ZPP-owned projections are removed'))
then('every generated worktree and dirty file is preserved')(support.bind_claim_step(support.claim_then, 'every generated worktree and dirty file is preserved'))
then('the unrelated user-owned worksets are unchanged')(support.bind_claim_step(support.claim_then, 'the unrelated user-owned worksets are unchanged'))
then('no active claim expires automatically before that recovery')(support.bind_claim_step(support.claim_then, 'no active claim expires automatically before that recovery'))
then('the orphaned ZPP-owned projection is removed')(support.bind_claim_step(support.claim_then, 'the orphaned ZPP-owned projection is removed'))
then('no user-owned workset, branch, or worktree is removed')(support.bind_claim_step(support.claim_then, 'no user-owned workset, branch, or worktree is removed'))
then('the durable catalog retains only active claims and unresolved generated work')(support.bind_claim_step(support.claim_then, 'the durable catalog retains only active claims and unresolved generated work'))
then('it retains no complete historical workset projections for the finalized codespaces')(support.bind_claim_step(support.claim_then, 'it retains no complete historical workset projections for the finalized codespaces'))
then('ZPP performs no automatic branch merge')(support.bind_claim_step(support.claim_then, 'ZPP performs no automatic branch merge'))
then('the recorded branch metadata remains available until the explicit reconciliation workflow gives it a disposition')(support.bind_claim_step(support.claim_then, 'the recorded branch metadata remains available until the explicit reconciliation workflow gives it a disposition'))
then('one codespace view records the writable and read-only repositories with their access roles')(support.bind_claim_step(support.claim_then, 'one codespace view records the writable and read-only repositories with their access roles'))
then('only the complete writable OpenSpec closure is exclusively claimed')(support.bind_claim_step(support.claim_then, 'only the complete writable OpenSpec closure is exclusively claimed'))
then('no read-only repository is treated as a conflict or receives an isolated worktree')(support.bind_claim_step(support.claim_then, 'no read-only repository is treated as a conflict or receives an isolated worktree'))
then('related stores of a read-only repository are omitted unless independently selected')(support.bind_claim_step(support.claim_then, 'related stores of a read-only repository are omitted unless independently selected'))
then('the same read-only repository can remain in both codespaces')(support.bind_claim_step(support.claim_then, 'the same read-only repository can remain in both codespaces'))
then('ZPP requires explicit codespace selection')(support.bind_claim_step(support.claim_then, 'ZPP requires explicit codespace selection'))
then('no claim or codespace view is changed')(support.bind_claim_step(support.claim_then, 'no claim or codespace view is changed'))
then('the projection contains the complete writable and read-only view')(support.bind_claim_step(support.claim_then, 'the projection contains the complete writable and read-only view'))
then('opening replaces the projection with the next structural generation')(support.bind_claim_step(support.claim_then, 'opening replaces the projection with the next structural generation'))
then('the superseded ZPP-owned projection is removed')(support.bind_claim_step(support.claim_then, 'the superseded ZPP-owned projection is removed'))
then('ZPP applies a new exclusively claimed writable member to the complete successor shape')(support.bind_claim_step(support.claim_then, 'ZPP applies a new exclusively claimed writable member to the complete successor shape'))
then('ZPP applies a new non-owning read-only member to the complete successor shape')(support.bind_claim_step(support.claim_then, 'ZPP applies a new non-owning read-only member to the complete successor shape'))
then('ZPP applies removal of the selected member to the complete successor shape')(support.bind_claim_step(support.claim_then, 'ZPP applies removal of the selected member to the complete successor shape'))
then('ZPP applies promotion from read-only to writable to the complete successor shape')(support.bind_claim_step(support.claim_then, 'ZPP applies promotion from read-only to writable to the complete successor shape'))
then('ZPP applies demotion from writable to read-only to the complete successor shape')(support.bind_claim_step(support.claim_then, 'ZPP applies demotion from writable to read-only to the complete successor shape'))
then('the narrower zpp codespace add command is unavailable')(support.bind_claim_step(support.claim_then, 'the narrower zpp codespace add command is unavailable'))
then('one successor identity and snapshot are calculated from the resulting roles, paths, and current full commits')(support.bind_claim_step(support.claim_then, 'one successor identity and snapshot are calculated from the resulting roles, paths, and current full commits'))
then('the successor atomically replaces the superseded active identity and writable claim')(support.bind_claim_step(support.claim_then, 'the successor atomically replaces the superseded active identity and writable claim'))
then('no unlocked interval or partial successor shape is observable')(support.bind_claim_step(support.claim_then, 'no unlocked interval or partial successor shape is observable'))
then('the superseded projection is removed or replaced with the successor projection')(support.bind_claim_step(support.claim_then, 'the superseded projection is removed or replaced with the successor projection'))
then('later file changes and commits do not automatically recalculate the successor identity')(support.bind_claim_step(support.claim_then, 'later file changes and commits do not automatically recalculate the successor identity'))
then('ZPP separately asks to release the superseded lock')(support.bind_claim_step(support.claim_then, 'ZPP separately asks to release the superseded lock'))
then('ZPP performs the atomic successor replacement')(support.bind_claim_step(support.claim_then, 'ZPP performs the atomic successor replacement'))
then('the original identity, claim, shape, and optional projection remain unchanged')(support.bind_claim_step(support.claim_then, 'the original identity, claim, shape, and optional projection remain unchanged'))
then('both replacement confirmations are preauthorized')(support.bind_claim_step(support.claim_then, 'both replacement confirmations are preauthorized'))
then('ZPP performs the same atomic successor replacement')(support.bind_claim_step(support.claim_then, 'ZPP performs the same atomic successor replacement'))
then('the edit is rejected before any partial successor becomes active')(support.bind_claim_step(support.claim_then, 'the edit is rejected before any partial successor becomes active'))
then('the existing identity and snapshot remain unchanged')(support.bind_claim_step(support.claim_then, 'the existing identity and snapshot remain unchanged'))
then('ZPP requests no replacement confirmation')(support.bind_claim_step(support.claim_then, 'ZPP requests no replacement confirmation'))
then('retained generated members transfer to the successor identity')(support.bind_claim_step(support.claim_then, 'retained generated members transfer to the successor identity'))
then('removed generated worktrees and branches remain reconciliation debt under the superseded identity')(support.bind_claim_step(support.claim_then, 'removed generated worktrees and branches remain reconciliation debt under the superseded identity'))
then('a demoted member references its canonical checkout read-only in the successor')(support.bind_claim_step(support.claim_then, 'a demoted member references its canonical checkout read-only in the successor'))
then('its generated worktree and branch remain superseded reconciliation debt')(support.bind_claim_step(support.claim_then, 'its generated worktree and branch remain superseded reconciliation debt'))
then('no generated content is deleted')(support.bind_claim_step(support.claim_then, 'no generated content is deleted'))
then('the active codespace and every writable and read-only member are inspectable with their access roles')(support.bind_claim_step(support.claim_then, 'the active codespace and every writable and read-only member are inspectable with their access roles'))
then('no read-only member is reported as claimed, generated, or pending reconciliation merely for joining the view')(support.bind_claim_step(support.claim_then, 'no read-only member is reported as claimed, generated, or pending reconciliation merely for joining the view'))
then('the installed agent guard rejects the mutation as read-only in the associated codespace')(support.bind_claim_step(support.claim_then, 'the installed agent guard rejects the mutation as read-only in the associated codespace'))
then('unsupported tools, arbitrary shell effects, manual editor actions, and cross-machine writes remain outside the guarantee')(support.bind_claim_step(support.claim_then, 'unsupported tools, arbitrary shell effects, manual editor actions, and cross-machine writes remain outside the guarantee'))
